version: '3'
services:
    studb:
        build: .
        image: yumemo/studb
        container_name: studb
        hostname: studb
        tty: true
        volumes:
          - .:/opt/studb
        ports:
          - "8000:8000"
